# Generated by Django 3.0.14 on 2023-03-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='order_id')),
                ('date', models.DateField(verbose_name='date')),
                ('user_id', models.IntegerField(verbose_name='user_id')),
                ('total_purchase', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total_purchase')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
            ],
        ),
    ]
